<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Story criterias covered by tests</title>

<style>
	body {
		font-family: verdana,arial,helvetica,sans-serif;
		font-size: 80%;
	}
	
	.story-name {
		background-color: #CC6600;
		margin-bottom: 1px;
	}
	
	.test { 
		font: boder;
		background-color: #66CC66;
		margin-bottom: 1px;
	}
	
	.test div {
		margin-left: 10px;
	}
	
</style>

</head>
<body>
<h1>Story criterias covered by tests</h1>

<div>
	$stories$
</div>

</body>
</html>